version: '3.9'

services:
  laravel:
    build:
      context: './prpnet-laravel'
    container_name: ${COMPOSE_PROJECT_NAME}_laravel
    env_file:
      - .env
    volumes:
      - ./prpnet-laravel:/var/www
    ports:
      - "9000:9000"
    networks:
      - prpnet

  nginx:
    image: nginx:alpine
    container_name: ${COMPOSE_PROJECT_NAME}_nginx
    restart: unless-stopped
    ports:
      - "${STACK_EXTERNAL_PORT}:8080"
    volumes:
      - ./prpnet-laravel:/var/www
      - ./prpnet-laravel/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - prpnet
