version: '3.9'

services:
  mysql:
    image: mysql:5.7
    container_name: ${COMPOSE_PROJECT_NAME}_mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: ${MYSQL_RANDOM_ROOT_PASSWORD}
    restart: unless-stopped
    volumes:
      - ./mysql/create_tables_mysql.sql:/docker-entrypoint-initdb.d/create_tables_mysql.sql
      - ./mysql/data:/var/lib/mysql
      - ./mysql/logs:/var/log/mysql
    ports:
      - "3306:3306"
    networks:
      - prpnet

  server:
    build:
      context: './prpnet-server'
    container_name: ${COMPOSE_PROJECT_NAME}_server
    command: "/bin/sh -c ./prpserver"
    environment:
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      PRPNET_HTML_TITLE: ${PRPNET_HTML_TITLE}
      PRPNET_PROJECT_TITLE: ${PRPNET_PROJECT_TITLE}
      PRPNET_PROJECT_NAME: ${PRPNET_PROJECT_NAME}
      PRPNET_SERVER_PORT: ${PRPNET_SERVER_PORT}
      PRPNET_SERVER_TYPE: ${PRPNET_SERVER_TYPE}
      PRPNET_ADMIN_EMAIL: ${PRPNET_ADMIN_EMAIL}
      PRPNET_ADMIN_PASSWORD: ${PRPNET_ADMIN_PASSWORD}
      PRPNET_DOUBLECHECK_ENABLED: ${PRPNET_DOUBLECHECK_ENABLED}
      PRPNET_DOUBLECHECKER: ${PRPNET_DOUBLECHECKER}
      PRPNET_MAX_WORKUNITS: ${PRPNET_MAX_WORKUNITS}
      PRPNET_MAX_CLIENTS: ${PRPNET_MAX_CLIENTS}
    volumes:
      - ./prpnet-server/sievefiles:/prpnet-server/sievefiles
    ports:
      - "$PRPNET_SERVER_PORT:$PRPNET_SERVER_PORT"
    depends_on:
      - mysql
    networks:
      - prpnet

networks:
  prpnet:
    driver: bridge
